### ISSUE TITLE
議程會用我電腦的時區顯示時間

### ISSUE THREAD

**Issue by pingooo** [COSCUP/2019#22]
我今天在紐約（和臺北時差 12 小時），看到的時間表如下圖。

![6611445891203072](https://user-images.githubusercontent.com/127246/59992015-b107bf80-9617-11e9-8fd1-429bdbc4e8fd.png)

看來是使用了我紐約的時區，這產生四個問題：

1. 日期錯誤：畫面底部的日期切換連結顯示出 8/16 8/17 8/18 三天。
2. 議程被切割：點選 8/17，看到臺北時間 8/17 12:00 - 17:10 和 8/18 9:00 - 12:00 的議程，因為這些時段是紐約的 8/17。
3. 我需要自己換算才知道哪個演講是臺北時間幾點。
4. 點選 8/18 則出現錯誤畫面，見下圖。

![6149918174216192](https://user-images.githubusercontent.com/127246/59992333-448dc000-9619-11e9-98ab-561268032854.png)

我覺得研討會的議程應該一律以臺北時間標示，以免造成混淆。

**Comment by pingooo** [comment]
補充說明：這對所有不在臺北時區的使用者都會造成混淆。

**Comment by bingluen** [comment]
We has did staticify for website, so at the moment you open website, it show time string by using `Asia/Taipei` timezone correctly.

After the API response of the schedule, website parse it using user's locale timezone and update schedule table.

That's why did you see schedule table show as your local timezone instead of  `Asia/Taipei` (where is location of conference).

And I try to fix it on 090ad717.

If this bug is not fixed after deploy, please reopen this issue.
